"""update_food_table

Revision ID: 6215dde7536c
Revises: c24acd1377f7
Create Date: 2026-01-16 17:50:47.823127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6215dde7536c'
down_revision = 'c24acd1377f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('is_vietnamese')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vietnamese', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
