"""add_converstion

Revision ID: a6c534f38089
Revises: 3b0749b9d2e9
Create Date: 2026-01-18 11:51:26.047286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c534f38089'
down_revision = '3b0749b9d2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('conversation_id')

    op.drop_table('conversations')
    # ### end Alembic commands ###
